"""empty message

Revision ID: 584e33e337de
Revises: d5c781d1350a
Create Date: 2023-12-06 13:48:45.649451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584e33e337de'
down_revision = 'd5c781d1350a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
