"""empty message

Revision ID: 6f1a0de3fe0c
Revises: 1c54f503b3f6
Create Date: 2023-12-05 13:44:39.835647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1a0de3fe0c'
down_revision = '1c54f503b3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role_type = sa.Enum('USER', 'ADMIN', name='role_types')
    role_type.create(op.get_bind())

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.alter_column('pdf',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', role_type, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.alter_column('pdf',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    role_type = sa.Enum('USER', 'ADMIN', name='role_types')
    role_type.drop(op.get_bind())

    # ### end Alembic commands ###
