"""empty message

Revision ID: 80aeb1d1a24c
Revises: 6f1a0de3fe0c
Create Date: 2023-12-05 16:02:49.873111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80aeb1d1a24c'
down_revision = '6f1a0de3fe0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
