"""empty message

Revision ID: 924749ffc631
Revises: 73d8ee7313c1
Create Date: 2023-12-07 17:54:23.477236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924749ffc631'
down_revision = '73d8ee7313c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'salary', ['salary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salary_id')

    # ### end Alembic commands ###
