"""empty message

Revision ID: 9875af5af6c3
Revises: ded5405577b0
Create Date: 2023-11-28 19:17:38.747759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9875af5af6c3'
down_revision = 'ded5405577b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('category')
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('category')

    op.create_table('category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='category_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='roles_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    # ### end Alembic commands ###
