"""empty message

Revision ID: a097b0b3fe20
Revises: 924749ffc631
Create Date: 2023-12-07 18:40:36.824934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a097b0b3fe20'
down_revision = '924749ffc631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_history', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_column('is_in_history')

    # ### end Alembic commands ###
