"""empty message

Revision ID: d5c781d1350a
Revises: 80aeb1d1a24c
Create Date: 2023-12-05 20:05:43.181150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c781d1350a'
down_revision = '80aeb1d1a24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_optimized', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_column('pdf_optimized')

    # ### end Alembic commands ###
